### ISSUE TITLE
为啥不能在python模块内使用多线程和协程去执行代码。php去获取

### ISSUE THREAD

**Issue by hgc357341051** [swoole/phpy#21]
为啥不能在python模块内使用多线程和协程去执行代码。php去获取，有办法吗，比如我只是在php cli模式下去执行

**Comment by Guxinpei** [comment]
> 为啥不能在python模块内使用多线程和协程去执行代码。php去获取，有办法吗，比如我只是在php cli模式下去执行

听起来似乎更适合symfony的Process来
搞定？我不确定，只是个想法。

**Comment by matyhtf** [comment]
python 代码中可以使用多线程和协程，只是不能在 php 层面使用。
