### ISSUE TITLE
安装扩展报错

### ISSUE THREAD

**Issue by bafeiyu** [swoole/phpy#26]
报错信息如下

`/usr/src/php/ext/phpy/src/bridge/core.cc:259:9:` error: 'zend_array_is_list' was not declared in this scope; did you mean 'zend_ast_is_list'?
  259 |     if (zend_array_is_list(ht)) {
      |         ^~~~~~~~~~~~~~~~~~
      |         zend_ast_is_list
/usr/src/php/ext/phpy/src/bridge/core.cc:258:17: warning: control reaches end of non-void function [-Wreturn-type]
  258 |     zend_array *ht = Z_ARRVAL_P(zv);
      |                 ^~
make: *** [Makefile:194: src/bridge/core.lo] Error 1`
不知道该怎么解决呢

**Comment by matyhtf** [comment]
需要 php8.1 以上版本
