### ISSUE TITLE
编译出错，PHP需要什么版本的

### ISSUE THREAD

**Issue by akin520** [swoole/phpy#3]
`In file included from /root/src/phpy/src/bridge/core.cc:18:
/root/src/phpy/include/phpy.h:200:15: error: ‘zend_result’ does not name a type; did you mean ‘zend_resource’?
  200 | static inline zend_result call_fn(
      |               ^~~~~~~~~~~
      |               zend_resource
/root/src/phpy/src/bridge/core.cc: In function ‘PyObject* array2py(zval*)’:
/root/src/phpy/src/bridge/core.cc:235:9: error: ‘zend_array_is_list’ was not declared in this scope; did you mean ‘zend_ast_is_list’?
  235 |     if (zend_array_is_list(ht)) {
      |         ^~~~~~~~~~~~~~~~~~
      |         zend_ast_is_list
/root/src/phpy/src/bridge/core.cc:234:17: warning: control reaches end of non-void function [-Wreturn-type]
  234 |     zend_array *ht = Z_ARRVAL_P(zv);
      |                 ^~
make: *** [Makefile:196: src/bridge/core.lo] Error 1`
PHP需要什么版本的，还有PYTHON make怎么指定，我是手工个修改里面的路径的

**Comment by matyhtf** [comment]
需要 8.1 以上的版本
