### ISSUE TITLE
docker内的liunx的python安装方式，能来个详细点的教程吗

### ISSUE THREAD

**Issue by hgc357341051** [swoole/phpy#31]
docker容器内的 Alpine Linux 系统的python安装方式，能来个详细点的教程吗，看的无从下手的样子，我用的是apk add python3命令一键安装的   ，安装路径是/usr/bin/python3，之后：./configure --with-python-dir=/usr/bin/python3，make一直报错
![image](https://github.com/swoole/phpy/assets/149741823/089fbac7-7ba6-490b-8c35-f98ce17cb56e)
![image](https://github.com/swoole/phpy/assets/149741823/e1647225-e4d9-4ba0-8721-c7b74e081ce7)

**Comment by he426100** [comment]
用 debian/ubuntu 吧，alpine貌似不行，你截图里的报错是因为你没有 `apk add python3-dev`，编译命令参考：`./configure --with-python-config=/usr/bin/python3-config`

**Comment by hgc357341051** [comment]
> 用 Debian/Ubuntu 吧，alpine貌似不行，你截图里的报错是因为你没有 ，编译命令参考：`apk add python3-dev``./configure --with-python-config=/usr/bin/python3-config`

很多人，很多项目，包括我，都是用了alpine容器，因为这个精简

**Comment by matyhtf** [comment]
使用 `--with-python-config=/usr/bin/python3-config`
