### ISSUE TITLE
导入第三方包的时候出现错误

### ISSUE THREAD

**Issue by Moxyu** [swoole/phpy#38]
![image](https://github.com/swoole/phpy/assets/49427582/5bd9732d-f65b-49ba-9089-3dd1eb5cd9f8)

![image](https://github.com/swoole/phpy/assets/49427582/e6e00621-f97b-4962-81fb-ad7e42bce3ad)

本地机器测试正常没问题，部署到服务器上就出现这个错误。

并且导入内置包没事，比如：PyCore::import('os');

能否帮忙分析下是什么原因导致的吗？

**Comment by Moxyu** [comment]
已解决这个问题，估计是swoole的问题，但是不知道为什么，重新编译了下swoole就可以了。

最后Phpy是真的强大，我司的目标检测业务，现在已经用PHP替代了。

**Comment by matyhtf** [comment]
赞，有问题可以向我们反馈
