### ISSUE TITLE
这种情况是什么原因？

### ISSUE THREAD

**Issue by Moxyu** [swoole/phpy#47]
![image](https://github.com/swoole/phpy/assets/49427582/550014a2-1b40-44d0-89ae-4f8b8760c2c9)

通常导入一些第三方包的时候会提示 Segmentation fault

内置包没有问题

1.0.3和1.0.4都这种问题

**Comment by matyhtf** [comment]
一般都是 so 库文件兼容性问题，建议检查 python 版本和 ld path 是否存在问题
