### ISSUE TITLE
模块加载报错

### ISSUE THREAD

**Issue by akin520** [swoole/phpy#5]
/usr/local/php83/bin/php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'phpy.so' (tried: /usr/local/php83/lib/php/extensions/no-debug-non-zts-20230831/phpy.so (/usr/local/php83/lib/php/extensions/no-debug-non-zts-20230831/phpy.so: undefined symbol: _ZNSt8ios_base4InitD1Ev), /usr/local/php83/lib/php/extensions/no-debug-non-zts-20230831/phpy.so.so (/usr/local/php83/lib/php/extensions/no-debug-non-zts-20230831/phpy.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP需要怎么编译，是不是不能启用php-fpm?

**Comment by matyhtf** [comment]
可能是 C++ 编译器的问题，试试修改 `config.m4` ，`CXXFLAGS` 添加 `-lstdc++`

**Comment by matyhtf** [comment]
已修复，与 #40 重复
