### ISSUE TITLE
PHP-FPM中如何使用？

### ISSUE THREAD

**Issue by fishfree** [swoole/phpy#52]
编译成功后，在/etc/php/8.2/fpm/php.ini里添加了extension=phpy，然后 systemctl restart php8.2-fpm 查看phpinfo()仍然没出现。cli/php.ini里加了后，php -m里马上就看到了

**Comment by matyhtf** [comment]
检查 phpinfo 中 php.ini 的准确位置。

**Comment by fishfree** [comment]
通过看log发现是需要手动追加LD_LIBRARY_PATH
