### ISSUE TITLE
Dockerfile.alpine执行构建镜像失败

### ISSUE THREAD

**Issue by hgc357341051** [swoole/phpy#55]
`{"stream":"Step 1/14 : FROM php:8.2.13-cli-alpine"}
{"stream":"\n"}
{"status":"Pulling from library/php","id":"8.2.13-cli-alpine"}
{"status":"Pulling fs layer","progressDetail":{},"id":"661ff4d9561e"}
{"status":"Pulling fs layer","progressDetail":{},"id":"fbc99979baa6"}
{"status":"Pulling fs layer","progressDetail":{},"id":"47536423e079"}
{"status":"Pulling fs layer","progressDetail":{},"id":"1be6d4fc569f"}
{"status":"Pulling fs layer","progressDetail":{},"id":"2014613d03d8"}
{"status":"Pulling fs layer","progressDetail":{},"id":"8af6c37b7e86"}
{"status":"Pulling fs layer","progressDetail":{},"id":"7926b59062ab"}
{"status":"Pulling fs layer","progressDetail":{},"id":"c0cfee82d291"}
{"status":"Pulling fs layer","progressDetail":{},"id":"1cf6a35fce59"}
{"status":"Waiting","progressDetail":{},"id":"1be6d4fc569f"}
{"status":"Waiting","progressDetail":{},"id":"8af6c37b7e86"}
{"status":"Waiting","progressDetail":{},"id":"2014613d03d8"}
{"status":"Waiting","progressDetail":{},"id":"7926b59062ab"}
{"status":"Waiting","progressDetail":{},"id":"1cf6a35fce59"}
{"status":"Waiting","progressDetail":{},"id":"c0cfee82d291"}
{"status":"Downloading","progressDetail":{"current":36422,"total":3408480},"progress":"[>                                                  ]  36.42kB/3.408MB","id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":1262,"total":1262},"progress":"[==================================================>]  1.262kB/1.262kB","id":"47536423e079"}
{"status":"Download complete","progressDetail":{},"id":"47536423e079"}
{"status":"Downloading","progressDetail":{"current":589382,"total":3408480},"progress":"[========>                                          ]  589.4kB/3.408MB","id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":28228,"total":2755737},"progress":"[>                                                  ]  28.23kB/2.756MB","id":"fbc99979baa6"}
{"status":"Downloading","progressDetail":{"current":1474118,"total":3408480},"progress":"[=====================>                             ]  1.474MB/3.408MB","id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":3022406,"total":3408480},"progress":"[============================================>      ]  3.022MB/3.408MB","id":"661ff4d9561e"}
{"status":"Verifying Checksum","progressDetail":{},"id":"661ff4d9561e"}
{"status":"Download complete","progressDetail":{},"id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":56900,"total":2755737},"progress":"[=>                                                 ]   56.9kB/2.756MB","id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":65536,"total":3408480},"progress":"[>                                                  ]  65.54kB/3.408MB","id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":228932,"total":2755737},"progress":"[====>                                              ]  228.9kB/2.756MB","id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":1638400,"total":3408480},"progress":"[========================>                          ]  1.638MB/3.408MB","id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":400964,"total":2755737},"progress":"[=======>                                           ]    401kB/2.756MB","id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":3342336,"total":3408480},"progress":"[=================================================> ]  3.342MB/3.408MB","id":"661ff4d9561e"}
{"status":"Extracting","progressDetail":{"current":3408480,"total":3408480},"progress":"[==================================================>]  3.408MB/3.408MB","id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":601668,"total":2755737},"progress":"[==========>                                        ]  601.7kB/2.756MB","id":"fbc99979baa6"}
{"status":"Pull complete","progressDetail":{},"id":"661ff4d9561e"}
{"status":"Downloading","progressDetail":{"current":1031748,"total":2755737},"progress":"[==================>                                ]  1.032MB/2.756MB","id":"fbc99979baa6"}
{"status":"Downloading","progressDetail":{"current":269,"total":269},"progress":"[==================================================>]     269B/269B","id":"1be6d4fc569f"}
{"status":"Verifying Checksum","progressDetail":{},"id":"1be6d4fc569f"}
{"status":"Download complete","progressDetail":{},"id":"1be6d4fc569f"}
{"status":"Downloading","progressDetail":{"current":1891908,"total":2755737},"progress":"[==================================>                ]  1.892MB/2.756MB","id":"fbc99979baa6"}
{"status":"Verifying Checksum","progressDetail":{},"id":"fbc99979baa6"}
{"status":"Download complete","progressDetail":{},"id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":32768,"total":2755737},"progress":"[>                                                  ]  32.77kB/2.756MB","id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":393216,"total":2755737},"progress":"[=======>                                           ]  393.2kB/2.756MB","id":"fbc99979baa6"}
{"status":"Downloading","progressDetail":{"current":122442,"total":12090156},"progress":"[>                                                  ]  122.4kB/12.09MB","id":"2014613d03d8"}
{"status":"Extracting","progressDetail":{"current":2293760,"total":2755737},"progress":"[=========================================>         ]  2.294MB/2.756MB","id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":2755737,"total":2755737},"progress":"[==================================================>]  2.756MB/2.756MB","id":"fbc99979baa6"}
{"status":"Downloading","progressDetail":{"current":982602,"total":12090156},"progress":"[====>                                              ]  982.6kB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":495,"total":495},"progress":"[==================================================>]     495B/495B","id":"8af6c37b7e86"}
{"status":"Download complete","progressDetail":{},"id":"8af6c37b7e86"}
{"status":"Pull complete","progressDetail":{},"id":"fbc99979baa6"}
{"status":"Extracting","progressDetail":{"current":1262,"total":1262},"progress":"[==================================================>]  1.262kB/1.262kB","id":"47536423e079"}
{"status":"Downloading","progressDetail":{"current":1597002,"total":12090156},"progress":"[======>                                            ]  1.597MB/12.09MB","id":"2014613d03d8"}
{"status":"Extracting","progressDetail":{"current":1262,"total":1262},"progress":"[==================================================>]  1.262kB/1.262kB","id":"47536423e079"}
{"status":"Pull complete","progressDetail":{},"id":"47536423e079"}
{"status":"Downloading","progressDetail":{"current":3194442,"total":12090156},"progress":"[=============>                                     ]  3.194MB/12.09MB","id":"2014613d03d8"}
{"status":"Extracting","progressDetail":{"current":269,"total":269},"progress":"[==================================================>]     269B/269B","id":"1be6d4fc569f"}
{"status":"Extracting","progressDetail":{"current":269,"total":269},"progress":"[==================================================>]     269B/269B","id":"1be6d4fc569f"}
{"status":"Downloading","progressDetail":{"current":5160522,"total":12090156},"progress":"[=====================>                             ]  5.161MB/12.09MB","id":"2014613d03d8"}
{"status":"Pull complete","progressDetail":{},"id":"1be6d4fc569f"}
{"status":"Downloading","progressDetail":{"current":6389322,"total":12090156},"progress":"[==========================>                        ]  6.389MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":171593,"total":16904612},"progress":"[>                                                  ]  171.6kB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":7495242,"total":12090156},"progress":"[==============================>                    ]  7.495MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":8478282,"total":12090156},"progress":"[===================================>               ]  8.478MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":515657,"total":16904612},"progress":"[=>                                                 ]  515.7kB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":9215562,"total":12090156},"progress":"[======================================>            ]  9.216MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":859721,"total":16904612},"progress":"[==>                                                ]  859.7kB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":9829962,"total":12090156},"progress":"[========================================>          ]   9.83MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":10935882,"total":12090156},"progress":"[=============================================>     ]  10.94MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":1375817,"total":16904612},"progress":"[====>                                              ]  1.376MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":11918922,"total":12090156},"progress":"[=================================================> ]  11.92MB/12.09MB","id":"2014613d03d8"}
{"status":"Verifying Checksum","progressDetail":{},"id":"2014613d03d8"}
{"status":"Download complete","progressDetail":{},"id":"2014613d03d8"}
{"status":"Extracting","progressDetail":{"current":131072,"total":12090156},"progress":"[>                                                  ]  131.1kB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":2408009,"total":16904612},"progress":"[=======>                                           ]  2.408MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":8912896,"total":12090156},"progress":"[====================================>              ]  8.913MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":3268169,"total":16904612},"progress":"[=========>                                         ]  3.268MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":12090156,"total":12090156},"progress":"[==================================================>]  12.09MB/12.09MB","id":"2014613d03d8"}
{"status":"Downloading","progressDetail":{"current":4472393,"total":16904612},"progress":"[=============>                                     ]  4.472MB/16.9MB","id":"7926b59062ab"}
{"status":"Pull complete","progressDetail":{},"id":"2014613d03d8"}
{"status":"Extracting","progressDetail":{"current":495,"total":495},"progress":"[==================================================>]     495B/495B","id":"8af6c37b7e86"}
{"status":"Extracting","progressDetail":{"current":495,"total":495},"progress":"[==================================================>]     495B/495B","id":"8af6c37b7e86"}
{"status":"Downloading","progressDetail":{"current":5676617,"total":16904612},"progress":"[================>                                  ]  5.677MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":2446,"total":2446},"progress":"[==================================================>]  2.446kB/2.446kB","id":"c0cfee82d291"}
{"status":"Verifying Checksum","progressDetail":{},"id":"c0cfee82d291"}
{"status":"Download complete","progressDetail":{},"id":"c0cfee82d291"}
{"status":"Pull complete","progressDetail":{},"id":"8af6c37b7e86"}
{"status":"Downloading","progressDetail":{"current":6880841,"total":16904612},"progress":"[====================>                              ]  6.881MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":3662,"total":19288},"progress":"[=========>                                         ]  3.662kB/19.29kB","id":"1cf6a35fce59"}
{"status":"Downloading","progressDetail":{"current":19288,"total":19288},"progress":"[==================================================>]  19.29kB/19.29kB","id":"1cf6a35fce59"}
{"status":"Verifying Checksum","progressDetail":{},"id":"1cf6a35fce59"}
{"status":"Download complete","progressDetail":{},"id":"1cf6a35fce59"}
{"status":"Downloading","progressDetail":{"current":8085065,"total":16904612},"progress":"[=======================>                           ]  8.085MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":9289289,"total":16904612},"progress":"[===========================>                       ]  9.289MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":10493513,"total":16904612},"progress":"[===============================>                   ]  10.49MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":11697737,"total":16904612},"progress":"[==================================>                ]   11.7MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":12901961,"total":16904612},"progress":"[======================================>            ]   12.9MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":14106185,"total":16904612},"progress":"[=========================================>         ]  14.11MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":15310409,"total":16904612},"progress":"[=============================================>     ]  15.31MB/16.9MB","id":"7926b59062ab"}
{"status":"Downloading","progressDetail":{"current":16514633,"total":16904612},"progress":"[================================================>  ]  16.51MB/16.9MB","id":"7926b59062ab"}
{"status":"Verifying Checksum","progressDetail":{},"id":"7926b59062ab"}
{"status":"Download complete","progressDetail":{},"id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":196608,"total":16904612},"progress":"[>                                                  ]  196.6kB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":2555904,"total":16904612},"progress":"[=======>                                           ]  2.556MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":4128768,"total":16904612},"progress":"[============>                                      ]  4.129MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":5701632,"total":16904612},"progress":"[================>                                  ]  5.702MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":6684672,"total":16904612},"progress":"[===================>                               ]  6.685MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":8060928,"total":16904612},"progress":"[=======================>                           ]  8.061MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":9633792,"total":16904612},"progress":"[============================>                      ]  9.634MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":10027008,"total":16904612},"progress":"[=============================>                     ]  10.03MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":11599872,"total":16904612},"progress":"[==================================>                ]   11.6MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":13565952,"total":16904612},"progress":"[========================================>          ]  13.57MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":14155776,"total":16904612},"progress":"[=========================================>         ]  14.16MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":15335424,"total":16904612},"progress":"[=============================================>     ]  15.34MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":15925248,"total":16904612},"progress":"[===============================================>   ]  15.93MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":16904612,"total":16904612},"progress":"[==================================================>]   16.9MB/16.9MB","id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":16904612,"total":16904612},"progress":"[==================================================>]   16.9MB/16.9MB","id":"7926b59062ab"}
{"status":"Pull complete","progressDetail":{},"id":"7926b59062ab"}
{"status":"Extracting","progressDetail":{"current":2446,"total":2446},"progress":"[==================================================>]  2.446kB/2.446kB","id":"c0cfee82d291"}
{"status":"Extracting","progressDetail":{"current":2446,"total":2446},"progress":"[==================================================>]  2.446kB/2.446kB","id":"c0cfee82d291"}
{"status":"Pull complete","progressDetail":{},"id":"c0cfee82d291"}
{"status":"Extracting","progressDetail":{"current":19288,"total":19288},"progress":"[==================================================>]  19.29kB/19.29kB","id":"1cf6a35fce59"}
{"status":"Extracting","progressDetail":{"current":19288,"total":19288},"progress":"[==================================================>]  19.29kB/19.29kB","id":"1cf6a35fce59"}
{"status":"Pull complete","progressDetail":{},"id":"1cf6a35fce59"}
{"status":"Digest: sha256:3b0171123d74f66754dbe4c425430a985710881f9e34c31263913555d8963354"}
{"status":"Status: Downloaded newer image for php:8.2.13-cli-alpine"}
{"stream":" ---> bcd00d062cc1\n"}
{"stream":"Step 2/14 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories"}
{"stream":"\n"}
{"stream":" ---> Running in 970eaf43f66f\n"}
{"stream":"Removing intermediate container 970eaf43f66f\n"}
{"stream":" ---> 1c96956f0b31\n"}
{"stream":"Step 3/14 : RUN apk add python3"}
{"stream":"\n"}
{"stream":" ---> Running in b599e8699b7c\n"}
{"stream":"fetch https://mirrors.ustc.edu.cn/alpine/v3.19/main/x86_64/APKINDEX.tar.gz\n"}
{"stream":"fetch https://mirrors.ustc.edu.cn/alpine/v3.19/community/x86_64/APKINDEX.tar.gz\n"}
{"stream":"(1/11) Installing libexpat (2.6.2-r0)\n"}
{"stream":"(2/11) Installing libbz2 (1.0.8-r6)\n"}
{"stream":"(3/11) Installing libffi (3.4.4-r3)\n"}
{"stream":"(4/11) Installing gdbm (1.23-r1)\n"}
{"stream":"(5/11) Installing libstdc++ (13.2.1_git20231014-r0)\n"}
{"stream":"(6/11) Installing mpdecimal (2.5.1-r2)\n"}
{"stream":"(7/11) Installing libpanelw (6.4_p20231125-r0)\n"}
{"stream":"(8/11) Installing python3 (3.11.9-r0)\n"}
{"stream":"(9/11) Installing python3-pycache-pyc0 (3.11.9-r0)\n"}
{"stream":"(10/11) Installing pyc (3.11.9-r0)\n"}
{"stream":"(11/11) Installing python3-pyc (3.11.9-r0)\n"}
{"stream":"Executing busybox-1.36.1-r15.trigger\n"}
{"stream":"OK: 60 MiB in 49 packages\n"}
{"stream":"Removing intermediate container b599e8699b7c\n"}
{"stream":" ---> 0faa63180c93\n"}
{"stream":"Step 4/14 : RUN apk add autoconf gcc g++ make python3-dev"}
{"stream":"\n"}
{"stream":" ---> Running in 262ccb92157f\n"}
{"stream":"(1/20) Installing m4 (1.4.19-r3)\n"}
{"stream":"(2/20) Installing perl (5.38.2-r0)\n"}
{"stream":"(3/20) Installing autoconf (2.71-r2)\n"}
{"stream":"(4/20) Installing libstdc++-dev (13.2.1_git20231014-r0)\n"}
{"stream":"(5/20) Installing jansson (2.14-r4)\n"}
{"stream":"(6/20) Installing zstd-libs (1.5.5-r8)\n"}
{"stream":"(7/20) Installing binutils (2.41-r0)\n"}
{"stream":"(8/20) Installing libgomp (13.2.1_git20231014-r0)\n"}
{"stream":"(9/20) Installing libatomic (13.2.1_git20231014-r0)\n"}
{"stream":"(10/20) Installing gmp (6.3.0-r0)\n"}
{"stream":"(11/20) Installing isl26 (0.26-r1)\n"}
{"stream":"(12/20) Installing mpfr4 (4.2.1-r0)\n"}
{"stream":"(13/20) Installing mpc1 (1.3.1-r1)\n"}
{"stream":"(14/20) Installing gcc (13.2.1_git20231014-r0)\n"}
{"stream":"(15/20) Installing musl-dev (1.2.4_git20230717-r4)\n"}
{"stream":"(16/20) Installing libc-dev (0.7.2-r5)\n"}
{"stream":"(17/20) Installing g++ (13.2.1_git20231014-r0)\n"}
{"stream":"(18/20) Installing make (4.4.1-r2)\n"}
{"stream":"(19/20) Installing pkgconf (2.1.0-r0)\n"}
{"stream":"(20/20) Installing python3-dev (3.11.9-r0)\n"}
{"stream":"Executing busybox-1.36.1-r15.trigger\n"}
{"stream":"OK: 375 MiB in 69 packages\n"}
{"stream":"Removing intermediate container 262ccb92157f\n"}
{"stream":" ---> fc16379800db\n"}
{"stream":"Step 5/14 : WORKDIR /work"}
{"stream":"\n"}
{"stream":" ---> Running in 7cb1d880fda1\n"}
{"stream":"Removing intermediate container 7cb1d880fda1\n"}
{"stream":" ---> 902c51742dbb\n"}
{"stream":"Step 6/14 : COPY . /work/phpy"}
{"stream":"\n"}
{"stream":" ---> 1993282589b5\n"}
{"stream":"Step 7/14 : RUN docker-php-source extract &&     cd /work/phpy && phpize &&     ./configure --with-python-config=/usr/bin/python3-config &&     make clean && make -j $(nproc)"}
{"stream":"\n"}
{"stream":" ---> Running in 8ee8d933f1e1\n"}
{"stream":"Cannot find config.m4. \nMake sure that you run '/usr/local/bin/phpize' in the top level source directory of the module\n\n"}
{"errorDetail":{"code":1,"message":"The command '/bin/sh -c docker-php-source extract &&     cd /work/phpy && phpize &&     ./configure --with-python-config=/usr/bin/python3-config &&     make clean && make -j $(nproc)' returned a non-zero code: 1"},"error":"The command '/bin/sh -c docker-php-source extract &&     cd /work/phpy && phpize &&     ./configure --with-python-config=/usr/bin/python3-config &&     make clean && make -j $(nproc)' returned a non-zero code: 1"}
image build failed!`
![image](https://github.com/swoole/phpy/assets/149741823/9de623c4-1772-4e39-845d-7badcf21fc31)

使用官方的Dockerfile：https://github.com/swoole/phpy/blob/main/Dockerfile.alpine
`FROM php:8.2.13-cli-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add python3
RUN apk add autoconf gcc g++ make python3-dev

WORKDIR /work
COPY . /work/phpy

RUN docker-php-source extract && \
    cd /work/phpy && phpize && \
    ./configure --with-python-config=/usr/bin/python3-config && \
    make clean && make -j $(nproc)

FROM php:8.2.13-cli-alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk add python3 bash

COPY --from=0 /work/phpy/modules/phpy.so /tmp
RUN cp /tmp/phpy.so $(php-config --extension-dir) && \
    docker-php-ext-enable phpy && \
    docker-php-source delete
RUN php --ri phpy

CMD ["bash"]`

**Comment by matyhtf** [comment]
https://hub.docker.com/repository/docker/phpswoole/phpy/general

直接使用官方提供的镜像

```php
docker pull phpswoole/phpy:1.0.5
```

**Comment by hgc357341051** [comment]
我手动去php:8.2.13-cli-alpine容器里去构建出phpy.so，加载提示：
`PHP         : /usr/local/bin/php 
Warning: PHP Startup: Unable to load dynamic library 'phpy.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/phpy.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20220829/phpy.so: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv: symbol not found), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/phpy.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20220829/phpy.so.so: No such file or directory)) in Unknown on line 0`
