### ISSUE TITLE
How do I target newer python versions

### ISSUE THREAD

**Issue by xander-st-aubyn** [swoole/phpy#70]
I am on el8 and php 8.1 and it is built against Python 3.6. How can I pick the python interpreter? Can I do it grammatically or would I have to recompile the extension?

Thank you for your attention.

**Comment by matyhtf** [comment]
The version of the Python dynamic link library that phpy connects to is determined at compile time, and there is no syntax for selecting the version.

Set the compilation parameter --with-python-config to select the Python version

```
phpize
./configure --with-python-config=/usr/bin/python3-config
```

**Comment by bozhinov** [comment]
@matyhtf sorry to pick that up but
the python lib is picked at compile time so no point in waiting for binaries in pecl ?

**Comment by matyhtf** [comment]
@bozhinov PECL only provides binary DLL files for the Windows system. Since phpy also requires a complete Python and PHP environment, providing only the phpy.dll for Windows is not meaningful. It is recommended to download the precompiled Windows binary package from the releases page.

**Comment by bozhinov** [comment]
That part is clear enough.

I find your idea genius.
current problem is the limitation of the package provided.
