### ISSUE TITLE
[Tools] lib generator

### ISSUE THREAD

**Issue by TheCelavi** [swoole/phpy#73]
Greetings! I am not sure how tools are intended to be used, but I have stumbled upon two problems:

1. When using "composer req swoole/phpy", and trying to use scripts from tools to generate php code from Python libs, error is emitted due to wrong path to autoload.php. Maybe I am using tools as not intended, or this should be more flexible to the installation location.
2. If I set properly path to autoload, generated code errors out. PHP mirror classes for Python libs are with empty constructors. Method do have arguments, but without types, nor return types.

Maybe I am doing something wrong, or there is a bug?

Btw - I honestly don't know how you guys pulled this mother f**** black voodoo magic, but it is nothing less than pure awesomeness. I am extremely impressed, level of integration is amazing 👏👏👏👏👏 great work! Well done!

**Comment by matyhtf** [comment]
The lib generator tool is currently in the experimental stage and has many unresolved issues. For instance, Python functions are untyped, and Python classes are not yet supported.

You may need to modify its code yourself.

**Comment by TheCelavi** [comment]
Thank you, this whole extension is amazing making all PHP ML libraries kinda unnecessary :)

Again, great work! 👏
