### ISSUE TITLE
make install报错

### ISSUE THREAD

**Issue by Fffhub** [swoole/phpy#8]
g++ -I. -I/root/inst/phpy -I/root/inst/phpy/include -I/root/inst/phpy/main -I/root/inst/phpy -I/www/server/php/81/include/php -I/www/server/php/81/include/php/main -I/www/server/php/81/include/php/TSRM -I/www/server/php/81/include/php/Zend -I/www/server/php/81/include/php/ext -I/www/server/php/81/include/php/ext/date/lib -I/opt/conda/include/python3.11 -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -z now -std=c++14 -DZEND_COMPILE_DL_EXT=1 -c /root/inst/phpy/src/python/class.cc -MMD -MF src/python/class.dep -MT src/python/class.lo  -fPIC -DPIC -o src/python/.libs/class.o
/root/inst/phpy/src/python/class.cc:50:1: sorry, unimplemented: non-trivial designated initializers not supported
 };
 ^
/root/inst/phpy/src/python/class.cc:50:1: sorry, unimplemented: non-trivial designated initializers not supported
/root/inst/phpy/src/python/class.cc:50:1: sorry, unimplemented: non-trivial designated initializers not supported
/root/inst/phpy/src/python/class.cc:50:1: sorry, unimplemented: non-trivial designated initializers not supported
/root/inst/phpy/src/python/class.cc:50:1: sorry, unimplemented: non-trivial designated initializers not supported
Makefile:241: recipe for target 'src/python/class.lo' failed
make: *** [src/python/class.lo] Error 1

**Comment by bafeiyu** [comment]
在docker里面操作安装扩展的时候也是报错，找不到原因

make: *** [Makefile:211: src/bridge/core.lo] Error 1
